#!/usr/bin/env python3
"""Demonstrate WADOE soft-MoE routing on a synthetic binary classification task.

============================================================================
DISCLAIMER
============================================================================
RESEARCH USE ONLY. NOT A MEDICAL DEVICE.

This script is for demonstrating the mechanics of the ``wadoe`` library --
routing, load balancing, expert diversity -- and nothing else. It is NOT a
medical device. It is NOT intended for clinical diagnosis, treatment,
screening, triage, or any other clinical use, of ADHD or of any other
condition. It must not be used to make decisions about real people.

All data below is SYNTHETIC: random noise generated by ``torch.randn`` with an
arbitrary label rule bolted on. No real patient data, no real clinical records,
and no real dataset is used, referenced, or reproduced here. The "ADHD" in the
filename is a nod to the origin of the WADOE acronym, not a claim about any
application. The library itself is domain-agnostic.

If you are researching clinical applications, you need ethics approval, privacy
and security review, external validation on held-out cohorts, fairness
analysis across subgroups, and regulatory review. None of that is demonstrated
here.
============================================================================

What this script shows
----------------------
1. Generating synthetic data with a learnable but deliberately coarse structure.
2. Putting a :class:`wadoe.WADOELayer` behind a mean-pooled classifier head.
3. Training with the combined :func:`wadoe.wadoe_loss`.
4. Printing expert usage and routing entropy every epoch, which is how you spot
   router collapse (one expert taking everything) and expert collapse (all
   experts becoming the same function).

Run it with::

    python examples/adhd_classification.py
"""

from __future__ import annotations

import math

import torch
import torch.nn as nn

from wadoe import (
    WADOELayer,
    diversity_loss,
    expert_usage,
    load_balance_loss,
    routing_entropy,
    set_seed,
    wadoe_loss,
)

DISCLAIMER = """
============================================================================
RESEARCH USE ONLY. NOT A MEDICAL DEVICE.
Not for clinical diagnosis or treatment of ADHD or any condition.
All data is synthetic. No real patient data is used.
============================================================================
"""

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
SEED = 0
N_SAMPLES = 256
N_TOKENS = 16
D_MODEL = 64
N_EXPERTS = 4
RANK = 8
EPOCHS = 30
BATCH_SIZE = 32
LR_ROUTER = 1e-3
LR_EXPERTS = 5e-4
LR_HEAD = 1e-3
# Start with a strong balancing weight to suppress collapse while the router is
# still near-uniform, then relax it.
LAMBDA_BALANCE_HOT = 0.10
LAMBDA_BALANCE = 0.01
LAMBDA_DIVERSITY = 0.05
HOT_STEPS = 100


class WADOEClassifier(nn.Module):
    """Mean-pool a WADOE layer and project to binary logits.

    The WADOE layer replaces the feed-forward sub-layer of a transformer block;
    the pooling and linear projection stand in for a sequence-level task head.

    Args:
        n_experts: Number of experts in the mixture.
        rank: Rank of each expert's low-rank adaptation.
        top_k: Experts kept per token. ``None`` for dense soft routing.
    """

    def __init__(
        self,
        d_model: int = D_MODEL,
        n_experts: int = N_EXPERTS,
        rank: int = RANK,
        top_k: int | None = 2,
    ) -> None:
        super().__init__()
        self.moe = WADOELayer(
            d_model=d_model,
            d_ff=4 * d_model,
            n_experts=n_experts,
            rank=rank,
            temperature=1.0,
            top_k=top_k,
        )
        self.head = nn.Linear(d_model, 1)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
        """Run the model.

        Args:
            x: Feature tensor of shape ``[B, T, d_model]``.

        Returns:
            A tuple ``(logits, aux)`` with ``logits`` of shape ``[B]`` and the
            layer's routing aux dict.
        """
        hidden, aux = self.moe(x)
        pooled = hidden.mean(dim=1)
        return self.head(pooled).squeeze(-1), aux


def make_synthetic_data() -> tuple[torch.Tensor, torch.Tensor]:
    """Build a synthetic classification dataset with learnable structure.

    Every sample is assigned a latent "expert group". That group's identity is
    injected into the first few feature dimensions, and the binary label is a
    deterministic function of the group parity. This is deliberately a toy
    signal: it exists so the router has *something* to specialise on and you can
    watch usage spread out, not because it models anything real.

    Returns:
        A tuple ``(features, labels)`` where ``features`` has shape
        ``[N_SAMPLES, N_TOKENS, D_MODEL]`` and ``labels`` has shape
        ``[N_SAMPLES]`` with values in ``{0.0, 1.0}``.
    """
    set_seed(SEED)

    group_signal = torch.randn(N_SAMPLES, N_EXPERTS) * 2.0
    group = group_signal.argmax(dim=-1)

    features = torch.randn(N_SAMPLES, N_TOKENS, D_MODEL)
    # Broadcast the group identity across the token axis into a few channels.
    features[:, :, :N_EXPERTS] += group_signal.unsqueeze(1)

    labels = (group % 2).float()
    return features, labels


def format_usage(usage: torch.Tensor) -> str:
    """Render per-expert usage as a fixed-width bar chart.

    Args:
        usage: 1-D tensor of per-expert frequencies summing to 1.

    Returns:
        A formatted string.
    """
    blocks = []
    for index, value in enumerate(usage.tolist()):
        bar = "#" * int(round(value * 20))
        blocks.append(f"e{index}:{value:5.3f} {bar:<20}")
    return "  ".join(blocks)


def main() -> None:
    """Train the toy model and report routing diagnostics per epoch."""
    print(DISCLAIMER)

    torch.manual_seed(SEED)
    features, labels = make_synthetic_data()
    print(
        f"Synthetic data: {N_SAMPLES} samples x {N_TOKENS} tokens x {D_MODEL} dims, "
        f"{N_EXPERTS} experts, rank {RANK}"
    )

    model = WADOEClassifier()
    optimizer = torch.optim.AdamW(
        [
            # A higher router LR is standard: the router is tiny and starts
            # near-uniform, so it can afford to move faster than the experts.
            {"params": model.moe.router.parameters(), "lr": LR_ROUTER},
            {"params": model.moe.experts.parameters(), "lr": LR_EXPERTS},
            {"params": model.head.parameters(), "lr": LR_HEAD},
        ],
        weight_decay=0.01,
    )

    n_batches = math.ceil(N_SAMPLES / BATCH_SIZE)
    global_step = 0
    max_entropy = math.log(N_EXPERTS)

    print(f"\n{'epoch':>5}  {'loss':>9}  {'task':>9}  {'balance':>9}  {'divers':>10}  {'entropy':>8}")
    print(f"{'':>5}  {'':>9}  {'':>9}  {'':>9}  {'':>10}  (max {max_entropy:.3f})")
    print("-" * 90)

    for epoch in range(1, EPOCHS + 1):
        permutation = torch.randperm(N_SAMPLES)
        epoch_totals = torch.zeros(5)

        for start in range(0, N_SAMPLES, BATCH_SIZE):
            index = permutation[start : start + BATCH_SIZE]
            batch_x = features[index]
            batch_y = labels[index]

            logits, aux = model(batch_x)
            task_loss = nn.functional.binary_cross_entropy_with_logits(logits, batch_y)

            lambda_balance = (
                LAMBDA_BALANCE_HOT if global_step < HOT_STEPS else LAMBDA_BALANCE
            )
            total, parts = wadoe_loss(
                task_loss,
                logits=aux["logits"],
                weights=aux["weights"],
                experts=model.moe.experts,
                lambda_balance=lambda_balance,
                lambda_div=LAMBDA_DIVERSITY,
            )

            optimizer.zero_grad()
            total.backward()
            optimizer.step()
            global_step += 1

            epoch_totals += torch.tensor([
                total.item(),
                task_loss.item(),
                parts["balance"].item(),
                parts["diversity"].item(),
                aux["entropy"].item(),
            ])

        means = epoch_totals / n_batches

        _, aux_full = model(features)
        usage = expert_usage(aux_full["weights"])

        print(
            f"{epoch:>5}  {means[0]:>9.5f}  {means[1]:>9.5f}  "
            f"{means[2]:>9.5f}  {means[3]:>10.2e}  {means[4]:>8.4f}"
        )
        if epoch % 10 == 0 or epoch == 1:
            print(f"       usage  {format_usage(usage)}")

    # ----------------------------------------------------------------- #
    # Final routing diagnostics
    # ----------------------------------------------------------------- #
    logits_final, aux_final = model(features)
    weights = aux_final["weights"]
    usage = expert_usage(weights)
    entropy = routing_entropy(aux_final["logits"])
    balance = load_balance_loss(aux_final["logits"], aux_final["weights"])
    diversity = diversity_loss(model.moe.experts)
    accuracy = ((logits_final > 0).float() == labels).float().mean()

    print("-" * 90)
    print(f"\nFinal expert usage      : {format_usage(usage)}")
    print(f"Routing entropy         : {entropy.item():.4f}  (uniform = {max_entropy:.4f})")
    print(
        f"Load-balance loss       : {balance.item():.4f}  "
        f"(1.0 uniform -> {N_EXPERTS}.0 collapsed)"
    )
    print(
        f"Diversity loss          : {diversity.item():.3e}  "
        f"(0.0 orthogonal -> {1.0 - 1.0 / N_EXPERTS:.4f} identical)"
    )
    print(f"Active experts per token: {(weights > 0).float().sum(-1).mean().item():.2f}")
    print(f"Train accuracy (toy)    : {accuracy.item():.4f}")

    # ----------------------------------------------------------------- #
    # How to read these numbers
    # ----------------------------------------------------------------- #
    print(
        """
Reading the diagnostics
-----------------------
* Usage near 1.0 for one expert and 0.0 for the rest is **router collapse**.
  Raise lambda_balance, raise the router learning rate, or reset the router
  weights. Raise the temperature to soften it.
* Usage spread evenly but train accuracy poor means the experts are not
  specialising. Check that your labels actually carry structure the experts can
  latch onto, and consider fewer experts or a lower rank.
* Entropy pinned at 0 means hard collapse. Entropy pinned at log(E) means the
  router is ignoring the mixture and acting like a uniform average, which wastes
  the capacity. You generally want entropy in the middle of the range.
* Run `diversity_loss(model.moe.experts)` to check expert homogenisation: 0 is
  orthogonal (ideal), and near 1 - 1/E means every expert has collapsed onto the
  same direction.

Reminder: this is synthetic noise with an arbitrary label rule. The numbers say
nothing about any real task, and this script supports no clinical use.
"""
    )


if __name__ == "__main__":
    main()
